// @ts-check
import { readdirSync } from "node:fs";
import { join } from "node:path";

import js from "@eslint/js";
import nextPlugin from "@next/eslint-plugin-next";
import reactHooks from "eslint-plugin-react-hooks";
import a11y from "eslint-plugin-jsx-a11y";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * One flat config for the whole monorepo.
 *
 * ── Why one file and one script ─────────────────────────────────────────
 *
 * The alternative is a config per workspace and a `lint` task fanned out by
 * turbo, which is what the other gates do. It buys per-package caching and costs
 * five copies of the same rule set — and a rule set in five places is one that
 * disagrees with itself the first time somebody tightens a rule in the app they
 * happen to be working in. ESLint has its own cache, the estate is four
 * workspaces, and `npm run lint` at the root is the only way to run it.
 *
 * ── Why nothing is a warning ────────────────────────────────────────────
 *
 * A warning does not fail, so it accumulates, and a lint run that prints two
 * hundred lines and exits 0 teaches everybody to stop reading it — the same
 * disease as the `next lint` script this replaces, which could not pass at all.
 * Every rule here is an error and the script runs with `--max-warnings 0`, so
 * the tree is clean or the command fails. A rule not worth fixing is a rule to
 * turn off HERE, with the reason written down, rather than one to leave shouting.
 *
 * ── What is deliberately absent ─────────────────────────────────────────
 *
 * · `eslint-config-next` — its peer range stops at ESLint 9, and it carries a
 *   legacy-config shim, React and a11y presets we have not chosen. The Next
 *   rules we do want come from `@next/eslint-plugin-next` directly, pinned to
 *   the same 15.5 as the app.
 * · `stylisticTypeChecked` and any formatting rules — no formatter is configured,
 *   and a linter arguing about commas is how a team learns to pass `--fix` at
 *   everything without reading it.
 */

/* The web app's feature slices, read from disk so the dependency rule below
   stays true as features are added. A hardcoded list would be wrong the first
   time somebody adds a module and right-looking for months. */
const FEATURES = readdirSync(join(import.meta.dirname, "apps/web/src/features"), {
  withFileTypes: true,
})
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name);

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/coverage/**",
      "apps/web/next-env.d.ts",
      // Generated by Prisma, and regenerated by `db:generate`.
      "packages/db/src/generated/**",
      /*
       * The handoff bundle, which is source to be COPIED rather than compiled.
       *
       * `design-kit/` is what `scripts/export-design-kit.sh` drops into a new
       * app: tokens, `cn.ts`, a navigation config and a reference page. Nothing
       * in this repo imports it, it is in no tsconfig and no workspace, and its
       * `@/` paths resolve in the app it is copied into rather than here. Linting
       * it would report on a file's destination, not on this codebase.
       */
      "design-kit/**",
    ],
  },

  js.configs.recommended,

  /*
   * Type-aware linting, scoped to TypeScript.
   *
   * `projectService` finds each file's own tsconfig, which matters here because
   * there is no root one: the web app's includes reach its `scripts/` too, and
   * the API's are split across `src`, `scripts` and `test`.
   *
   * The type-checked set is the point of running a linter on this codebase at
   * all. `no-floating-promises` and `no-misused-promises` are the two rules that
   * pay for it — a dropped `await` inside one of the transactions this product is
   * built on is exactly the bug nothing else here would catch, because the happy
   * path still returns.
   */
  {
    files: ["**/*.ts", "**/*.tsx"],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      /* `_previous` is the first argument of every server action — the shape
         `useActionState` hands them — so an underscore means "the signature
         requires this and the body does not". */
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      /* `x != null` is deliberate in a few places — it asks "neither null nor
         undefined", which is one comparison rather than two. Everything else is
         strict. */
      eqeqeq: ["error", "always", { null: "ignore" }],
      /* A status union gains a member and every switch over it has to answer for
         itself. `considerDefaultExhaustiveForUnions` keeps the switches that
         already handle the rest in a default. */
      "@typescript-eslint/switch-exhaustiveness-check": [
        "error",
        { considerDefaultExhaustiveForUnions: true },
      ],
      /*
       * OFF: `async` is part of a contract here as often as it is a mistake.
       *
       * `IdService.sessionCode` is async because every sibling in that family
       * hits a counter and callers await the lot; a Next config's `headers()` is
       * async because the framework's type says so. Neither is a missing await,
       * and the rule cannot tell an interface from an oversight. What it would
       * actually catch — a promise nobody waits for — is `no-floating-promises`,
       * which stays on.
       */
      "@typescript-eslint/require-await": "off",
    },
  },

  /*
   * The dependency rule, enforced.
   *
   * `tokens → primitives → patterns → features → routes`, one way. CLAUDE.md
   * calls a primitive importing from a feature a bug, and until now nothing said
   * so except the prose: the seam held because people read the file, which is the
   * definition of a rule that will eventually be missed.
   */
  {
    files: ["apps/web/src/components/**", "apps/web/src/lib/**", "apps/web/src/config/**"],
    rules: {
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/features/*", "@/features/**", "**/features/**"],
              message:
                "The dependency rule is one-way: primitives, patterns and lib may not import a feature. Move what is shared down a layer, or pass it in as a prop.",
            },
          ],
        },
      ],
    },
  },

  /*
   * And the other half of it: a feature may not reach into another feature.
   *
   * One block per slice, because "not this directory" cannot be said once. The
   * services are the reason — `features/<x>/server/<x>-service.ts` is the only place
   * that knows where data comes from, so a screen that reaches sideways into
   * another slice's service silently doubles that seam.
   */
  ...FEATURES.map((feature) => ({
    files: [`apps/web/src/features/${feature}/**`],
    rules: {
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/features/*", "@/features/*/**", `!@/features/${feature}`, `!@/features/${feature}/**`],
              message:
                "Features do not import each other. Two thin callers of one shared primitive or one guarded endpoint is the shape this product wants; one caller imported across a slice boundary is not.",
            },
          ],
        },
      ],
    },
  })),

  /*
   * The web app: React, and the rules that only mean something in a browser.
   *
   * `coreWebVitals` over `recommended` because the extra rules are the ones with
   * a user-visible cost — a sync script, an unoptimised font, a page navigated
   * with an anchor instead of a Link.
   */
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    plugins: {
      "@next/next": nextPlugin,
      "jsx-a11y": a11y,
      "react-hooks": reactHooks,
    },
    /* Where the app actually is. Without it the plugin looks for `pages/` beside
       this config, does not find one, and says so on every run — and
       `no-html-link-for-pages` has nothing to check against. */
    settings: {
      next: { rootDir: "apps/web" },
      /*
       * What the design system's primitives actually render.
       *
       * Without this, `jsx-a11y` only inspects raw DOM elements — and almost
       * nothing in this app is a raw DOM element. `<Button>` is a `<button>`,
       * `<Link>` is an `<a>`, and the field wrappers are their controls, so the
       * rules follow them through instead of stopping at a capital letter.
       *
       * `Icon` is deliberately absent: it renders an inline `<svg aria-hidden>`,
       * and mapping it to `img` would demand alt text on decoration that is
       * correctly hidden from a screen reader.
       */
      "jsx-a11y": {
        components: {
          Button: "button",
          Link: "a",
          Select: "select",
          SelectField: "select",
          TextField: "input",
          TextareaField: "textarea",
        },
      },
    },
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      /*
       * The Next plugin ships some of its rules as warnings, and a warning is
       * against the house rule: it does not fail, so it accumulates. Promoted to
       * errors on the way in, which is also what `--max-warnings 0` would do to
       * them — except visibly, in the config, rather than by accident in the
       * script.
       */
      ...Object.fromEntries(
        Object.keys(nextPlugin.flatConfig.coreWebVitals.rules).map((rule) => [rule, "error"]),
      ),
      ...reactHooks.configs.recommended.rules,
      /*
       * STRICT rather than recommended, which here means the option objects stop
       * excusing things: `allowExpressionValues` comes off
       * `no-static-element-interactions` and `no-noninteractive-tabindex`, and the
       * role allowances come off the element-to-role rules. The codebase passed
       * `recommended` with nothing to fix, so the weaker set would have been a
       * badge rather than a check.
       */
      ...a11y.flatConfigs.strict.rules,
      /*
       * Four the presets leave out or drop, each a real class of defect:
       *
       * · `anchor-ambiguous-text` — "click here" and "read more" are the whole
       *   link as a screen reader lists it, and this product's links are verbs.
       *   `strict` drops it; it comes back.
       * · `lang` — a document with no language makes a screen reader guess at
       *   pronunciation for every word on it.
       * · `no-aria-hidden-on-focusable` — hiding something the keyboard can still
       *   reach is worse than either, because the focus lands nowhere announceable.
       */
      "jsx-a11y/anchor-ambiguous-text": "error",
      "jsx-a11y/lang": "error",
      "jsx-a11y/no-aria-hidden-on-focusable": "error",
      /*
       * `prefer-tag-over-role` was tried and turned off, which is worth recording
       * rather than quietly not adding.
       *
       * It reported eleven, and following its advice would have made every one of
       * them worse. Eight are `role="img"` with an `aria-label` on a composed
       * graphic — an avatar's initials, a donut, a stacked bar, a sparkline — which
       * is the recommended way to name an inline SVG and cannot be written as
       * `<img alt>` without giving up the markup that draws it. Two are
       * `role="status"` live regions, one of which computes its role
       * (`intent === "danger" ? "alert" : "status"`), and `<output>` can express
       * neither. The last is `role="progressbar"`, where `<progress>` cannot be
       * styled to the design.
       *
       * The case the rule is really for — `role="button"` on a div — does not
       * occur here, and would be caught anyway by `interactive-supports-focus`,
       * `click-events-have-key-events` and `no-static-element-interactions`, all
       * of which are on in their strict form.
       */
      "jsx-a11y/prefer-tag-over-role": "off",
      /*
       * A label's text is three levels down in this design system — the control,
       * then a wrapper, then the name and its hint as two spans — and the rule's
       * default only looks two deep. It is the nesting that is real here, not a
       * missing name: `depth` exists for exactly this.
       */
      "jsx-a11y/label-has-associated-control": ["error", { depth: 3 }],
    },
  },

  /*
   * The probe scripts, which read untyped JSON on purpose.
   *
   * `apps/api/scripts/verify-*.ts` sign in over HTTP and assert on what the
   * server ACTUALLY returns — that is the whole reason they exist rather than
   * being unit tests against the services. `await response.json()` is `any` by
   * construction, and 1,128 of the 1,281 findings on the first run were this one
   * shape: reaching into a wire payload the script is there to inspect.
   *
   * Typing those payloads would mean a second declaration of every contract,
   * maintained by hand, in the one place whose job is to distrust the first. The
   * unsafe family is off HERE and nowhere else; `apps/api/src` and the web app
   * keep it, because in product code an `any` is a hole rather than a payload.
   */
  {
    files: ["apps/api/scripts/**/*.ts", "packages/db/scripts/**/*.ts"],
    rules: {
      /*
       * `condition ? ok(…) : bad(…)` as a statement is how every one of these
       * files is written — seventy-four times — and it reads as a table of
       * assertions rather than as an expression somebody forgot to use. In
       * product code an expression statement is usually a mistake, so this is
       * allowed here and nowhere else.
       */
      "@typescript-eslint/no-unused-expressions": ["error", { allowTernary: true }],
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },

  /* The web suites are the same kind of file, written by the same hand. */
  {
    files: ["apps/web/scripts/**/*.ts"],
    rules: {
      "@typescript-eslint/no-unused-expressions": ["error", { allowTernary: true }],
    },
  },

  /*
   * Server code may use the word `module`, because that is what they are called.
   *
   * `@next/next/no-assign-module-variable` guards against shadowing the bundler's
   * CJS `module` in browser code. `MODULES` is this product's permission
   * vocabulary — nine of them, named in the nav rail — and
   * `for (const module of MODULES)` inside a `"use server"` file never reaches a
   * browser bundle. Renaming a domain word to satisfy a bundling rule that does
   * not apply is the wrong way round.
   */
  {
    files: ["apps/web/src/**/server/**/*.ts", "apps/web/src/server/**/*.ts"],
    rules: { "@next/next/no-assign-module-variable": "off" },
  },

  /*
   * The prototype walker runs in Node and hands functions to the page.
   *
   * `document` inside a `page.evaluate` callback is the browser's, evaluated
   * there rather than here, so the file legitimately names both sets of globals.
   */
  {
    files: ["docs/prototype/check.mjs"],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },

  /* Everything outside the browser. */
  {
    files: [
      "apps/api/**/*.ts",
      "packages/**/*.ts",
      "apps/web/scripts/**/*.ts",
      "**/*.mjs",
    ],
    languageOptions: { globals: globals.node },
  },

  /*
   * Plain JavaScript, of which there are three files: this config, the audit
   * explainer and the prototype walker. None is in a tsconfig, so type-aware
   * rules have nothing to read.
   */
  {
    files: ["**/*.mjs", "**/*.js"],
    extends: [tseslint.configs.disableTypeChecked],
  },
);
