import { z } from "zod";
import { pageQuerySchema, queryBoolean } from "../common/page.js";
import { moneyMinor } from "../common/money.js";

/**
 * Two billing levels, ONE installment engine.
 *
 * Retail bills the student through `student_fee_ledger`; college bills the
 * institution through `college_contracts`. `fee_installments` hangs off
 * exactly one of them (invariant 4), so there is one schedule engine, one
 * drawer and one overdue state machine rather than two of each drifting apart.
 *
 * Every amount is integer minor units (paise) as a decimal string. Parse it as
 * a big integer — never a float, at any layer, including display (invariant 5).
 */

export const installmentStatusSchema = z.enum(["PENDING", "PARTIALLY_PAID", "PAID", "OVERDUE"]);
export const ledgerStatusSchema = z.enum(["UNPAID", "PARTIALLY_PAID", "PAID_FULL", "OVERDUE"]);
export const contractStatusSchema = z.enum(["DRAFT", "ACTIVE", "PAID", "CANCELLED"]);
export const paymentModeSchema = z.enum(["UPI", "CREDIT_CARD", "DEBIT_CARD", "CASH", "OTHER"]);

export const installmentSchema = z.object({
  installmentId: z.string(),
  /** Exactly one of these is set. Never both, never neither. */
  ledgerId: z.string().nullable(),
  contractId: z.string().nullable(),
  installmentNumber: z.number().int(),
  amountMinor: moneyMinor,
  paidAmountMinor: moneyMinor,
  /** Derived: amount − paid. Never stored. */
  outstandingMinor: moneyMinor,
  dueDate: z.string(),
  status: installmentStatusSchema,
  paidAt: z.string().nullable(),
  reminderSentAt: z.string().nullable(),
});

export type Installment = z.infer<typeof installmentSchema>;

export const paymentSchema = z.object({
  transactionId: z.string(),
  transactionCode: z.string(),
  installmentId: z.string(),
  amountMinor: moneyMinor,
  paymentMode: paymentModeSchema,
  externalTransactionId: z.string().nullable(),
  paidAt: z.string(),
  bankOrHandle: z.string().nullable(),
  receiptNumber: z.string().nullable(),
  isReversal: z.boolean(),
  reversesTransactionId: z.string().nullable(),
  reversalReason: z.string().nullable(),
  createdAt: z.string(),
});

export type Payment = z.infer<typeof paymentSchema>;

/**
 * The master list is a SUMMARY: installment counts run from one to a hundred,
 * so the schedule lives in the student's own ledger rather than the register.
 */
export const ledgerSummarySchema = z.object({
  ledgerId: z.string(),
  studentId: z.string(),
  studentCode: z.string(),
  studentName: z.string(),
  courseId: z.string(),
  courseName: z.string().nullable(),
  batchId: z.string().nullable(),
  batchCode: z.string().nullable(),
  courseValueMinor: moneyMinor,
  /** GENERATED by the database from the two values above. */
  discountAmountMinor: moneyMinor.nullable(),
  enrolmentValueMinor: moneyMinor,
  totalPaidMinor: moneyMinor,
  balancePendingMinor: moneyMinor,
  status: ledgerStatusSchema,
  /** "2/4" — paid of scheduled. */
  installmentsPaid: z.number().int(),
  installmentsTotal: z.number().int(),
  nextDueDate: z.string().nullable(),
  overdueCount: z.number().int(),
});

export type LedgerSummary = z.infer<typeof ledgerSummarySchema>;

/**
 * One installment with the receipts posted against it.
 *
 * A payment is never an edit to the installment — it is its own row, and a
 * reversal is another. That is what makes a ledger auditable: the balance is
 * derived from the entries, not overwritten in place.
 */
export const installmentWithPaymentsSchema = installmentSchema.extend({
  payments: z.array(paymentSchema),
});

export type InstallmentWithPayments = z.infer<typeof installmentWithPaymentsSchema>;

/**
 * What `GET /fee-ledger/:ledgerId` returns: the summary plus the schedule, each
 * row carrying its own receipts.
 *
 * Declared here rather than left implied — an undocumented field is invisible
 * to the OpenAPI document, so the mobile and third-party clients cannot see it.
 */
export const ledgerDetailSchema = ledgerSummarySchema.extend({
  installments: z.array(installmentWithPaymentsSchema),
});

export type LedgerDetail = z.infer<typeof ledgerDetailSchema>;

/**
 * The register's headline figures.
 *
 * RETAIL ONLY by construction, like the register itself — billing follows
 * segment, so a college student has no individual ledger to total (invariant
 * 3). Institutional money is the contracts list and is counted there.
 *
 * Summed in the database in minor units: these reach lakh and crore scale,
 * and a float loses paise on the way to the screen.
 */
export const ledgerRegisterSummarySchema = z.object({
  courseValueMinor: moneyMinor,
  discountMinor: moneyMinor,
  enrolmentValueMinor: moneyMinor,
  collectedMinor: moneyMinor,
  outstandingMinor: moneyMinor,
  /** Ledgers with at least one installment past its due date. */
  overdueAccounts: z.number().int(),
  ledgers: z.number().int(),
});

export type LedgerRegisterSummary = z.infer<typeof ledgerRegisterSummarySchema>;

export const ledgerQuerySchema = pageQuerySchema.extend({
  studentId: z.string().optional(),
  courseId: z.string().optional(),
  batchId: z.string().optional(),
  status: ledgerStatusSchema.optional(),
  /** Only ledgers carrying at least one overdue installment. */
  overdueOnly: queryBoolean.optional(),
});

export type LedgerQuery = z.infer<typeof ledgerQuerySchema>;

// ── Contracts (ADR 0003) ──────────────────────────────────────────────────

export const commercialBasisSchema = z.enum(["PER_STUDENT", "FLAT_COHORT"]);
export const headcountBasisSchema = z.enum(["REQUIREMENT", "ENROLLED", "MANUAL"]);

export const contractSchema = z.object({
  contractId: z.string(),
  contractCode: z.string(),
  collegeId: z.string(),
  collegeName: z.string().nullable().optional(),
  requirementId: z.string().nullable(),
  batchId: z.string().nullable(),
  batchCode: z.string().nullable().optional(),
  courseId: z.string(),
  courseName: z.string().nullable().optional(),
  commercialBasis: commercialBasisSchema,
  perStudentRateMinor: moneyMinor.nullable(),
  flatCohortPriceMinor: moneyMinor.nullable(),
  billableHeadcount: z.number().int(),
  headcountBasis: headcountBasisSchema,
  /** GENERATED — rate × headcount, or the flat price. */
  computedTotalMinor: moneyMinor.nullable(),
  overrideTotalMinor: moneyMinor.nullable(),
  overrideReason: z.string().nullable(),
  /** GENERATED — the override if set, else the computed total. The only
   *  total the ledger, invoices and reports read. */
  totalValueMinor: moneyMinor.nullable(),
  advanceCollectedMinor: moneyMinor,
  totalPaidMinor: moneyMinor,
  balancePendingMinor: moneyMinor,
  status: contractStatusSchema,
  signedAt: z.string().nullable(),
  createdAt: z.string(),
  deletedAt: z.string().nullable(),
  installmentsPaid: z.number().int().optional(),
  installmentsTotal: z.number().int().optional(),
  /** How many students are actually on the linked batch's roster. */
  enrolledHeadcount: z.number().int().optional(),
});

export type Contract = z.infer<typeof contractSchema>;

export const contractQuerySchema = pageQuerySchema.extend({
  collegeId: z.string().optional(),
  courseId: z.string().optional(),
  status: contractStatusSchema.optional(),
});

export type ContractQuery = z.infer<typeof contractQuerySchema>;

export const createContractSchema = z
  .object({
    collegeId: z.string().min(1, "Select a college"),
    courseId: z.string().min(1, "Select a course"),
    requirementId: z.string().optional(),
    batchId: z.string().optional(),
    commercialBasis: commercialBasisSchema,
    /** Required when the basis is PER_STUDENT. */
    perStudentRate: z.string().optional(),
    /** Required when the basis is FLAT_COHORT. */
    flatCohortPrice: z.string().optional(),
    billableHeadcount: z.number().int().min(0).max(10_000).default(0),
    headcountBasis: headcountBasisSchema.default("REQUIREMENT"),
    /** Only when the negotiated total differs from the computed one. */
    overrideTotal: z.string().optional(),
    overrideReason: z.string().trim().max(500).optional(),
    notes: z.string().trim().max(4000).optional(),
  })
  .superRefine((v, ctx) => {
    if (v.commercialBasis === "PER_STUDENT") {
      if (!v.perStudentRate) {
        ctx.addIssue({ code: "custom", path: ["perStudentRate"], message: "Enter the per-student rate" });
      }
      if (v.billableHeadcount <= 0) {
        ctx.addIssue({ code: "custom", path: ["billableHeadcount"], message: "A per-student contract needs a headcount" });
      }
    }
    if (v.commercialBasis === "FLAT_COHORT" && !v.flatCohortPrice) {
      ctx.addIssue({ code: "custom", path: ["flatCohortPrice"], message: "Enter the flat cohort price" });
    }
    // An unexplained discount is the first thing an audit asks about.
    if (v.overrideTotal && !v.overrideReason) {
      ctx.addIssue({ code: "custom", path: ["overrideReason"], message: "Say why the negotiated total differs" });
    }
  });

export type CreateContractInput = z.infer<typeof createContractSchema>;

export const updateContractSchema = z
  .object({
    perStudentRate: z.string().optional(),
    flatCohortPrice: z.string().optional(),
    billableHeadcount: z.number().int().min(0).max(10_000).optional(),
    headcountBasis: headcountBasisSchema.optional(),
    overrideTotal: z.string().nullable().optional(),
    overrideReason: z.string().trim().max(500).nullable().optional(),
    status: contractStatusSchema.optional(),
    signedAt: z.string().optional(),
    notes: z.string().trim().max(4000).optional(),
  })
  .superRefine((v, ctx) => {
    if (v.overrideTotal && !v.overrideReason) {
      ctx.addIssue({ code: "custom", path: ["overrideReason"], message: "Say why the negotiated total differs" });
    }
  });

export type UpdateContractInput = z.infer<typeof updateContractSchema>;

// ── Schedules and payments ────────────────────────────────────────────────

export const scheduleRowSchema = z.object({
  amount: z.string().min(1, "Enter the amount"),
  dueDate: z.string().min(1, "Choose a due date"),
});

/** One schedule engine, so this shape serves both parents. */
export const setScheduleSchema = z.object({
  installments: z.array(scheduleRowSchema).min(1, "Author at least one installment").max(100),
});

export type SetScheduleInput = z.infer<typeof setScheduleSchema>;

export const recordPaymentSchema = z
  .object({
    installmentId: z.string().min(1, "Select an installment"),
    amount: z.string().min(1, "Enter the amount received"),
    mode: paymentModeSchema,
    /** Required for every mode except cash. */
    transactionId: z.string().trim().max(120).optional(),
    paidAt: z.string().min(1, "When was it received?"),
    bankOrHandle: z.string().trim().max(160).optional(),
    receiptNumber: z.string().trim().max(64).optional(),
    notes: z.string().trim().max(400).optional(),
  })
  .superRefine((v, ctx) => {
    if (v.mode !== "CASH" && !v.transactionId) {
      ctx.addIssue({
        code: "custom",
        path: ["transactionId"],
        message: "A transaction ID is required for every mode except cash",
      });
    }
  });

export type RecordPaymentInput = z.infer<typeof recordPaymentSchema>;

/**
 * A receipt is a financial record — there is no delete. The correction is a
 * reversing entry, which is why this carries a reason.
 */
export const reversePaymentSchema = z.object({
  reason: z.string().trim().min(1, "Say why the receipt is being reversed").max(500),
});

export type ReversePaymentInput = z.infer<typeof reversePaymentSchema>;

/**
 * Who a reminder for this installment actually reaches. Resolved from the
 * installment's PARENT, never from a stored column (invariant 6) — which is
 * what stops a college's students receiving an invoice reminder.
 */
export const reminderRecipientSchema = z.object({
  installmentId: z.string(),
  /** STUDENT for a retail ledger, COLLEGE for an institutional contract. */
  recipientType: z.enum(["STUDENT", "COLLEGE"]),
  recipientId: z.string(),
  name: z.string(),
  email: z.string(),
  amountMinor: moneyMinor,
  outstandingMinor: moneyMinor,
  dueDate: z.string(),
});

export type ReminderRecipient = z.infer<typeof reminderRecipientSchema>;

export const cronResultSchema = z.object({
  remindersDue: z.number().int(),
  markedOverdue: z.number().int(),
  parentsRederived: z.number().int(),
});

export type CronResult = z.infer<typeof cronResultSchema>;

// ── The receipt ───────────────────────────────────────────────────────────

/**
 * A receipt is the document a payer keeps. It is issued, not stored.
 *
 * Every field below is derived at read time from the transaction and its
 * parents, which is deliberate: a receipt snapshotted at payment would go on
 * saying a reversed payment was received. Reversal is the ONLY correction a
 * financial record has here — there is no delete anywhere in this module — so
 * the receipt has to be able to show, afterwards, that it was reversed.
 *
 * **Its number is `transactionCode`**, the TXN-… generated on save. Business
 * IDs are generated, never typed (invariant 9), and a receipt number is the
 * strongest case for that rule there is. The separate `externalReference` is
 * the OTHER thing: the bank's reference or the number off a physical receipt
 * book, typed by the operator because it comes from outside this system.
 */
export const receiptPayerSchema = z.object({
  /**
   * Which one this is follows the segment, exactly as billing does
   * (invariant 3) and exactly as a reminder's recipient does (invariant 6) —
   * resolved from the installment's PARENT, never a stored column. A college
   * student has no ledger, so a receipt against a college cohort is addressed
   * to the institution and never to one of its students.
   */
  type: z.enum(["STUDENT", "COLLEGE"]),
  id: z.string(),
  code: z.string(),
  name: z.string(),
  email: z.string(),
  phone: z.string().nullable(),
  /** The institution's address on a college receipt; a student has none held. */
  address: z.string().nullable(),
});

export type ReceiptPayer = z.infer<typeof receiptPayerSchema>;

/** Who issued it. Configured, because the schema holds no organisation row. */
export const receiptIssuerSchema = z.object({
  name: z.string(),
  address: z.string().nullable(),
  gstin: z.string().nullable(),
  email: z.string().nullable(),
  phone: z.string().nullable(),
});

export const receiptSchema = z.object({
  transactionId: z.string(),
  /** TXN-…, generated on save. This IS the receipt number. */
  receiptNumber: z.string(),
  /** A reversal is a credit note; the screen says so on its face. */
  kind: z.enum(["PAYMENT", "REVERSAL"]),
  issuedAt: z.string(),
  paidAt: z.string(),

  amountMinor: moneyMinor,
  /** Stated twice on purpose: figures take a pen, words do not. */
  amountInWords: z.string(),
  paymentMode: paymentModeSchema,
  /** The UPI reference or bank transaction id, as typed. */
  externalTransactionId: z.string().nullable(),
  bankOrHandle: z.string().nullable(),
  /** The operator's own reference — a physical receipt book number. */
  externalReference: z.string().nullable(),
  notes: z.string().nullable(),

  payer: receiptPayerSchema,
  issuer: receiptIssuerSchema,

  /** What it was for. */
  courseName: z.string().nullable(),
  batchCode: z.string().nullable(),
  installmentId: z.string(),
  installmentNumber: z.number().int(),
  installmentOfTotal: z.number().int(),
  installmentAmountMinor: moneyMinor,
  installmentDueDate: z.string(),

  /** Where the account stands NOW — not where it stood when this was taken. */
  installmentPaidMinor: moneyMinor,
  installmentOutstandingMinor: moneyMinor,
  accountTotalMinor: moneyMinor,
  accountPaidMinor: moneyMinor,
  accountOutstandingMinor: moneyMinor,

  recordedByName: z.string().nullable(),

  /** Set when this receipt has since been reversed — stamped across its face. */
  reversedAt: z.string().nullable(),
  reversedByReceiptNumber: z.string().nullable(),
  reversalReason: z.string().nullable(),
  /** Set when this IS the reversal, naming the receipt it corrects. */
  reversesReceiptNumber: z.string().nullable(),
});

export type Receipt = z.infer<typeof receiptSchema>;
