"use client";

import { useActionState, useState } from "react";
import { useFormStatus } from "react-dom";
import { formatRupees, fromWire, type Contract } from "@gurukulam/contracts";

import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Field } from "@/components/ui/field";
import { createContract, updateContract } from "@/features/ledger/server/actions";
import { IDLE, type FormState } from "@/lib/form";

const inputClass =
  "h-12 w-full rounded-tile border border-hairline-strong bg-surface px-4 text-body text-ink placeholder:text-ink-subtle focus:border-brand focus:outline-none";

export interface Option {
  id: string;
  label: string;
}

/** Rupees as typed, from a decimal string on the wire. */
const rupees = (minor: string | null): string =>
  minor === null ? "" : formatRupees(fromWire(minor), { symbol: false });

/**
 * A college contract, on one of its two commercial bases.
 *
 * Both bases are real, and which one applies is a commercial fact rather than
 * a preference: PER_STUDENT bills a rate times a headcount, FLAT_COHORT bills
 * one price for the cohort however many turn up. The form shows only the
 * fields the chosen basis needs, because a per-student rate sitting beside a
 * flat price is an invitation to fill in both and wonder which one billed.
 *
 * The total is GENERATED by the database — rate × headcount, or the flat
 * price — and the override is a separate, explained thing. An unexplained
 * discount is the first question an audit asks, which is why the reason is
 * required the moment an override is entered.
 *
 * The COLLEGE and COURSE are set once. They decide who is billed and for what,
 * so changing either would make the instalments already raised belong to a
 * different agreement — which is why the update contract omits them and this
 * form shows them as read-only when editing.
 */
export function ContractForm({
  colleges,
  courses,
  contract,
}: {
  colleges: readonly Option[];
  courses: readonly Option[];
  contract?: Contract;
}) {
  const editing = contract !== undefined;
  const action = editing ? updateContract.bind(null, contract.contractId) : createContract;
  const [state, submit] = useActionState<FormState, FormData>(action, IDLE);
  const [basis, setBasis] = useState(contract?.commercialBasis ?? "PER_STUDENT");
  const [override, setOverride] = useState(contract?.overrideTotalMinor !== null && contract !== undefined);
  const error = (key: string) => state.fields?.[key];

  return (
    <Card>
      <form action={submit} className="flex flex-col gap-6">
        {state.message === undefined ? null : (
          <Alert intent="danger" title="That contract was not saved">
            {state.message}
          </Alert>
        )}

        {editing ? (
          <>
            {/* Not fields. See the note above the component. */}
            <input type="hidden" name="collegeId" value={contract.collegeId} />
            <input type="hidden" name="courseId" value={contract.courseId} />
            <div className="grid gap-6 sm:grid-cols-2">
              <ReadOnly label="College" value={contract.collegeName ?? "—"} />
              <ReadOnly label="Course" value={contract.courseName ?? "—"} />
            </div>
          </>
        ) : (
          <div className="grid gap-6 sm:grid-cols-2">
            <Field
              htmlFor="collegeId"
              label="College"
              required
              hint="Who is billed. A college student has no individual ledger — the institution pays."
              {...(error("collegeId") === undefined ? {} : { error: error("collegeId")! })}
            >
              <Select id="collegeId" name="collegeId" defaultValue="">
                <option value="" disabled>
                  Choose a college…
                </option>
                {colleges.map((option) => (
                  <option key={option.id} value={option.id}>
                    {option.label}
                  </option>
                ))}
              </Select>
            </Field>

            <Field
              htmlFor="courseId"
              label="Course"
              required
              {...(error("courseId") === undefined ? {} : { error: error("courseId")! })}
            >
              <Select id="courseId" name="courseId" defaultValue="">
                <option value="" disabled>
                  Choose a course…
                </option>
                {courses.map((option) => (
                  <option key={option.id} value={option.id}>
                    {option.label}
                  </option>
                ))}
              </Select>
            </Field>
          </div>
        )}

        <Field
          htmlFor="commercialBasis"
          label="Commercial basis"
          required
          hint="How this engagement is priced. It decides which of the two fields below applies."
          {...(error("commercialBasis") === undefined ? {} : { error: error("commercialBasis")! })}
        >
          <Select
            id="commercialBasis"
            name="commercialBasis"
            value={basis}
            onChange={(event) => setBasis(event.target.value as typeof basis)}
          >
            <option value="PER_STUDENT">Per student — a rate times a headcount</option>
            <option value="FLAT_COHORT">Flat cohort — one price, however many attend</option>
          </Select>
        </Field>

        {basis === "PER_STUDENT" ? (
          <div className="grid gap-6 sm:grid-cols-3">
            <Field
              htmlFor="perStudentRate"
              label="Rate per student"
              required
              {...(error("perStudentRate") === undefined ? {} : { error: error("perStudentRate")! })}
            >
              <input
                id="perStudentRate"
                name="perStudentRate"
                className={inputClass}
                defaultValue={rupees(contract?.perStudentRateMinor ?? null)}
                placeholder="12,000"
                inputMode="decimal"
              />
            </Field>

            <Field
              htmlFor="billableHeadcount"
              label="Billable headcount"
              required
              hint="Zero bills nothing — a silent zero rather than an error."
              {...(error("billableHeadcount") === undefined ? {} : { error: error("billableHeadcount")! })}
            >
              <input
                id="billableHeadcount"
                name="billableHeadcount"
                type="number"
                min={0}
                max={10000}
                className={inputClass}
                defaultValue={contract?.billableHeadcount ?? ""}
              />
            </Field>

            <Field
              htmlFor="headcountBasis"
              label="Counted from"
              hint="Where the number comes from when it is recomputed."
              {...(error("headcountBasis") === undefined ? {} : { error: error("headcountBasis")! })}
            >
              <Select
                id="headcountBasis"
                name="headcountBasis"
                defaultValue={contract?.headcountBasis ?? "REQUIREMENT"}
              >
                <option value="REQUIREMENT">What the college asked for</option>
                <option value="ENROLLED">Who is actually on the roster</option>
                <option value="MANUAL">Typed, and left alone</option>
              </Select>
            </Field>
          </div>
        ) : (
          <Field
            htmlFor="flatCohortPrice"
            label="Flat cohort price"
            required
            hint="One price for the cohort, whatever the final headcount."
            {...(error("flatCohortPrice") === undefined ? {} : { error: error("flatCohortPrice")! })}
          >
            <input
              id="flatCohortPrice"
              name="flatCohortPrice"
              className={inputClass}
              defaultValue={rupees(contract?.flatCohortPriceMinor ?? null)}
              placeholder="4,50,000"
              inputMode="decimal"
            />
          </Field>
        )}

        <div className="flex flex-col gap-4 rounded-well border border-hairline p-4">
          <label className="flex cursor-pointer items-start gap-3">
            <input
              type="checkbox"
              checked={override}
              onChange={(event) => setOverride(event.target.checked)}
              className="mt-1 size-4 shrink-0 accent-brand"
            />
            <span className="text-body-sm text-ink">
              <span className="font-semibold">The negotiated total differs from the computed one.</span>{" "}
              The computed total is generated by the database; this replaces it, and every invoice
              and report reads the replacement.
            </span>
          </label>

          {override ? (
            <div className="grid gap-6 sm:grid-cols-2">
              <Field
                htmlFor="overrideTotal"
                label="Negotiated total"
                required
                {...(error("overrideTotal") === undefined ? {} : { error: error("overrideTotal")! })}
              >
                <input
                  id="overrideTotal"
                  name="overrideTotal"
                  className={inputClass}
                  defaultValue={rupees(contract?.overrideTotalMinor ?? null)}
                  inputMode="decimal"
                />
              </Field>
              <Field
                htmlFor="overrideReason"
                label="Why"
                required
                hint="An unexplained discount is the first thing an audit asks about."
                {...(error("overrideReason") === undefined ? {} : { error: error("overrideReason")! })}
              >
                <input
                  id="overrideReason"
                  name="overrideReason"
                  className={inputClass}
                  defaultValue={contract?.overrideReason ?? ""}
                  placeholder="Repeat engagement — 8% agreed with the principal."
                />
              </Field>
            </div>
          ) : null}
        </div>

        {editing ? (
          <div className="grid gap-6 sm:grid-cols-2">
            <Field
              htmlFor="status"
              label="Status"
              {...(error("status") === undefined ? {} : { error: error("status")! })}
            >
              <Select id="status" name="status" defaultValue={contract.status}>
                <option value="DRAFT">Draft</option>
                <option value="ACTIVE">Active</option>
                <option value="PAID">Paid</option>
                <option value="CANCELLED">Cancelled</option>
              </Select>
            </Field>
            <Field
              htmlFor="signedAt"
              label="Signed"
              {...(error("signedAt") === undefined ? {} : { error: error("signedAt")! })}
            >
              <input
                id="signedAt"
                name="signedAt"
                type="date"
                className={inputClass}
                defaultValue={contract.signedAt?.slice(0, 10) ?? ""}
              />
            </Field>
          </div>
        ) : null}

        <Field
          htmlFor="notes"
          label="Notes"
          {...(error("notes") === undefined ? {} : { error: error("notes")! })}
        >
          <textarea
            id="notes"
            name="notes"
            rows={3}
            className="w-full rounded-tile border border-hairline-strong bg-surface px-4 py-3 text-body text-ink focus:border-brand focus:outline-none"
            defaultValue={contract?.notes ?? ""}
          />
        </Field>

        <div className="flex justify-end border-t border-hairline pt-5">
          <Submit editing={editing} />
        </div>
      </form>
    </Card>
  );
}

function ReadOnly({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col gap-1.5">
      <span className="text-body-sm font-medium text-ink">{label}</span>
      <span className="flex h-12 items-center rounded-tile bg-surface-sunken px-4 text-body text-ink-muted">
        {value}
      </span>
    </div>
  );
}

/** A select that draws its own chevron — the native arrow cannot be positioned. */
function Select(props: React.SelectHTMLAttributes<HTMLSelectElement>) {
  const { className, children, ...rest } = props;
  return (
    <div className="relative">
      <select {...rest} className={`${inputClass} appearance-none ${className ?? ""}`}>
        {children}
      </select>
      <span
        aria-hidden
        className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-ink-muted"
      >
        ▾
      </span>
    </div>
  );
}

function Submit({ editing }: { editing: boolean }) {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending}>
      {pending ? "Saving…" : editing ? "Save changes" : "Create the contract"}
    </Button>
  );
}
