import type { Metadata } from "next";
import Link from "next/link";
import { can, formatRupees, fromWire } from "@gurukulam/contracts";

import { DetailRow } from "@/components/patterns/detail-row";
import { PageHeader } from "@/components/patterns/page-header";
import { PageBody } from "@/components/patterns/page-section";
import { Alert } from "@/components/ui/alert";
import { Card, CardHeader } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { ContractForm, type Option } from "@/features/ledger/components/contract-form";
import { ScheduleEditor } from "@/features/ledger/components/schedule-editor";
import { getContract } from "@/features/ledger/server/ledger-service";
import { requireModule } from "@/server/principal";

export const metadata: Metadata = { title: "Contract" };

const STATUS = {
  DRAFT: { intent: "neutral", label: "Draft" },
  ACTIVE: { intent: "info", label: "Active" },
  PAID: { intent: "success", label: "Paid" },
  CANCELLED: { intent: "danger", label: "Cancelled" },
} as const;

const money = (minor: string | null) =>
  minor === null ? "—" : formatRupees(fromWire(minor), { paise: false });

/**
 * One contract: what is billed, and the instalments that bill it.
 *
 * Both on one screen because they are one decision. An operator changing a
 * headcount wants to see immediately what that does to the schedule, and a
 * schedule that no longer adds up to the total is the mistake this pairing
 * exists to catch.
 *
 * The schedule closes once money has been collected. The API is the authority
 * on that; this asks it the same question the API would and says so up front
 * rather than letting somebody rewrite a plan they cannot save.
 */
export default async function ContractDetailPage({
  params,
  searchParams,
}: {
  params: Promise<{ contractId: string }>;
  searchParams: Promise<{ created?: string; saved?: string }>;
}) {
  const principal = await requireModule("feeLedger");
  const { contractId } = await params;
  const flags = await searchParams;
  const contract = await getContract(contractId);
  const status = STATUS[contract.status];
  const mayEdit = can(principal, "feeLedger", "edit");

  const collected = fromWire(contract.totalPaidMinor) > 0n;

  // The college and course are fixed once set, so the form only ever needs the
  // one option each — it renders them read-only when editing.
  const colleges: Option[] = [{ id: contract.collegeId, label: contract.collegeName ?? "—" }];
  const courses: Option[] = [{ id: contract.courseId, label: contract.courseName ?? "—" }];

  return (
    <PageBody>
      <PageHeader
        eyebrow={contract.contractCode}
        title={contract.collegeName ?? "Contract"}
        description={`${contract.courseName ?? "—"}${contract.batchCode === null || contract.batchCode === undefined ? "" : ` · ${contract.batchCode}`}`}
        breadcrumbs={[
          { label: "Fee ledger", href: "/fee-ledger" },
          { label: "Contracts", href: "/fee-ledger/contracts" },
          { label: contract.contractCode },
        ]}
        action={<StatusPill intent={status.intent}>{status.label}</StatusPill>}
      />

      {flags.created === "1" ? (
        <Alert intent="success" title="Contract created">
          Nothing falls due yet. Author the instalment schedule below.
        </Alert>
      ) : null}
      {flags.saved === "1" ? (
        <Alert intent="success" title="Saved">
          The commercials are updated. Check the schedule still adds up to the total.
        </Alert>
      ) : null}

      <div className="grid gap-8 xl:grid-cols-3">
        <div className="flex flex-col gap-6 xl:col-span-2">
          {mayEdit ? (
            <ContractForm colleges={colleges} courses={courses} contract={contract} />
          ) : (
            <Card>
              <CardHeader as="h2" title="Commercials" />
              <dl>
                <DetailRow label="Basis" value={contract.commercialBasis === "PER_STUDENT" ? "Per student" : "Flat cohort"} />
                <DetailRow label="Rate per student" value={money(contract.perStudentRateMinor)} variant="figure" />
                <DetailRow label="Flat cohort price" value={money(contract.flatCohortPriceMinor)} variant="figure" />
                <DetailRow label="Billable headcount" value={String(contract.billableHeadcount)} variant="figure" />
                <DetailRow label="Notes" value={contract.notes ?? "—"} />
              </dl>
            </Card>
          )}
        </div>

        <div className="flex flex-col gap-6">
          <Card>
            <CardHeader
              as="h2"
              title="What it comes to"
              description="The computed total is generated by the database. Everything downstream reads the total value."
            />
            <dl>
              <DetailRow label="Computed" value={money(contract.computedTotalMinor)} variant="figure" />
              <DetailRow label="Negotiated override" value={money(contract.overrideTotalMinor)} variant="figure" />
              {contract.overrideReason === null ? null : (
                <DetailRow label="Why" value={contract.overrideReason} />
              )}
              <DetailRow label="Total value" value={money(contract.totalValueMinor)} strong variant="figure" />
              <DetailRow label="Collected" value={money(contract.totalPaidMinor)} variant="figure" />
              <DetailRow label="Outstanding" value={money(contract.balancePendingMinor)} strong variant="figure" />
              {contract.enrolledHeadcount === undefined ? null : (
                <DetailRow
                  label="Actually enrolled"
                  value={`${contract.enrolledHeadcount} on the roster`}
                />
              )}
            </dl>
            {contract.enrolledHeadcount === undefined ||
            contract.enrolledHeadcount === contract.billableHeadcount ||
            contract.commercialBasis !== "PER_STUDENT" ? null : (
              <p className="mt-4 border-t border-hairline pt-4 text-body-sm text-warning-strong">
                Billing {contract.billableHeadcount} but {contract.enrolledHeadcount}{" "}
                {contract.enrolledHeadcount === 1 ? "student is" : "students are"} on the roster.
                That is legitimate when the college committed to a number — but it is worth knowing.
              </p>
            )}
          </Card>

          {mayEdit ? (
            <ScheduleEditor
              parent="contract"
              parentId={contract.contractId}
              totalMinor={contract.totalValueMinor}
              existing={[]}
              locked={collected}
              lockedReason="Money has been collected against this contract. Rewriting the plan would orphan receipts already issued against its instalments."
            />
          ) : null}

          <p className="text-body-sm text-ink-muted">
            <Link href="/fee-ledger/contracts" className="text-gold underline-offset-4 hover:underline">
              Back to contracts
            </Link>
          </p>
        </div>
      </div>
    </PageBody>
  );
}
